### ISSUE TITLE
Checks Result List webview is not displaying scroll bar

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1024]
**Describe the bug**
When verifying issue 881, the scroll bar feature available in PT 9 is missing in Check Result List Webview

**To Reproduce**
On the Check Results List webview, when there are more results generated on a 'Rerun', there is no way to see all the results.

**Expected behavior**
Have a scroll bar to view all the generated results.

![ScrollBarNeeded](https://github.com/user-attachments/assets/a2cff5c4-c481-4a70-beb5-a722295c9d8e)

**Comment by tjcouch-sil** [comment]
I did some reflecting on this issue. I was wondering if the problem was that we don't set up the iframe to stay its size and add a scroll bar or something. But I realized changing the default styles that go on the iframe would very likely cause confusion and bugs. I think people will generally expect their iframes to work like a normal web page whose layout increases in size automatically. The default will work fine in many situations.

Unfortunately, the default doesn't always work. In some situations, the web view author may need to set up some styles to constrain the size of the web view in order to do nice flexbox or similar complex layout things. Here are two examples I found of setting styles such that they constrain the size of the iframe's document:

https://github.com/paranext/paranext-core/blob/main/extensions/src/platform-scripture/src/inventory.web-view.scss#L1-L12
https://github.com/paranext/paratext-bible-internal-extensions/blob/main/src/paratext-bible-send-receive/src/send-receive.web-view.scss#L1-L11

I wonder if this issue has more to do with the iframe's document not being constrained than it does with the results list component itself.

**Comment by roopa0222** [comment]
Closing the issue as it is not planned.

**Comment by tjcouch-sil** [comment]
By not baking in some default CSS, we leave the iframes to do what the browser normally does by default. Web developers are likely expecting this and would be confused if we changed it.

To set your iframe contents to the size of the iframe container, you can [add `tw-h-screen` to a div at the top of your iframe](https://github.com/paranext/paranext-core/blob/63002a66072ec4eb508ca654b22ea4fb8271a1af/extensions/src/paratext-registration/src/paratext-registration.web-view.tsx#L147). There are of course other ways to do this, but this is a pretty quick and easy way to do it. That way, flex divs and other such things will stay in the iframe and not flow past the iframe.
