### ISSUE TITLE
Add tsc typechecking to pre-commit to catch Typescript errors

### ISSUE THREAD

**Issue by tombogle** [paranext/paranext-core#1085]
Needs to be configured to only do TS compilation on the parts of the monorepo that actually have our code, probably somewhat similar to the way eslint is configured.

**Comment by irahopkinson** [comment]
Once typechecking is set up we can set `'consistent-return': 'off',` in all eslint configs (`.eslintrc.js`) since https://typescript-eslint.io/rules/consistent-return/ recommends using tsconfig's `noImplicitReturns` option which is already on (except in `platform-bible-react` and `platform-bible-utils`).
