### ISSUE TITLE
Remove markup from Text Collection display

### ISSUE THREAD

**Issue by GlennPruitt** [paranext/paranext-core#1111]
Remove markers from the Scripture text that is displayed in the Text Collection.  Footnotes, cross references (and any other content that appear between start and end markers) should also be removed.  Refer to Paratext 9 Text Collection as an example.

**Comment by lyonsil** [comment]
We can replace the left-side view of text with the scripture editor in read-only mode.

**Comment by tjcouch-sil** [comment]
Ended up just displaying the verse plain text because of #1131 I found while working on this.

[Added Verse Plain Text project interface by tjcouch-sil · Pull Request #1132 · paranext/paranext-core](https://github.com/paranext/paranext-core/pull/1132)
[Text collection verse display changed to use plain text instead of usfm by tjcouch-sil · Pull Request #35 · paranext/paratext-bible-extensions](https://github.com/paranext/paratext-bible-extensions/pull/35)
