### ISSUE TITLE
Can not place a cursor (or select text) in combined verses in Scripture Editor

### ISSUE THREAD

**Issue by roopa0222** [paranext/paranext-core#1201]
**Describe the bug**
In PB, set the BCV at Philippians 2 and open zzz2 project in Scripture Editor.  Notice that the cursor can not be placed in the combined verse at 2:25-26. It is not possible to select the a word in the combined verse.

**To Reproduce**

Download  zzz2 2020-10-20 project from the shared drive https://drive.google.com/file/d/1MAfSYLyRxONiiOCvUgdQY5rbqKQkJBvt/view
2. Open `Scripture Editor` from the PB main hamburger menu and select zzz2 project
3. Set the BCV to Philippians 2
4. Notice that the cursor can not be moved using arrow keys nor can be placed in the combined verses at Philippians 2:25-26 or 29-30

**Expected behavior**
Should be able to place cursor and be able to select text at the combined verses

https://github.com/user-attachments/assets/014e7755-f8d9-4f42-8da4-6807af6d9a93

**Comment by irahopkinson** [comment]
Note this is not a problem in the editor itself.

**Comment by irahopkinson** [comment]
Actually, it's likely not a problem in PB given a related issue that @lyonsil found. From the zzz6 project, add a comment on a word in RUT 1:3 (you'll need to enable comments) and observe you can't move or click your cursor into the comment. Also note that verses 1-2 are combined. At this stage I haven't been able to reproduce either issue in the editor repo.

**Comment by lyonsil** [comment]
Yes, this is happening because comments are being sent to the webview before the USJ has been updated. I think it is entirely unrelated to this problem. You will see log messages like that even on pages where comments are marked properly. This is something we'll want to address before we remove the feature flag/setting and just make comments enabled altogether. As long as it's behind the feature flag, having more logging is going to be helpful for us to track down problems.

**Comment by irahopkinson** [comment]
Although I still can't reproduce the problem in the editor repo, it is caused by a combined verse returning `NaN` (Not a Number) for the `verseNum`. In the editor repo the BC control shows `NaN` but in PB it shows the last verse number. The problem @lyonsil found is related in that it "finds" v1 instead of v3 and since v1 is `NaN` we get the same problem.
