### ISSUE TITLE
Deploy updated Marketplace to Rancher

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#1218]
- [ ] Once the code is ready, build and deploy an image of the marketplace services to Rancher.
- [ ] Write down how to do this if it isn't written down already.

**Comment by tombogle** [comment]
**Testing**
Since this change is primarily a rebranding effort, the underlying functionality does not necessarily need to be tested exhaustively. That said, it probably has never been tested rigorously, so any effort put toward that could be beneficial. It will ultimately need some UX review and probably some usability testing as well. The only (minimal) user-facing documentation I can find for the site is on the the [About page](https://marketplace-qa.paratext.bible/about). Here are a few ideas for testing (some of which cross the blurry line into UX testing):

- Before logging in, check each page for visual/layout issues or places where use of colors or images does not seem to follow branding guidelines.
- Log in (using Paratext Registry credentials) and make sure that process works as expected.
- Re-check each page for visual/layout issues
- On the Publishers page, attempt to create a publisher.
- On the Publish page, attempt to upload one or more test extensions.
- Access the API endpoint(s) to ensure that the information was correctly stored. (Alternatively, this could be checked inside Paratext 10 Studio by installing the marketplace extension, but checking the API itself might be easier and it would eliminate other possible points of failure.) _Check back here for API URLs..._
- On the Extensions page, attempt to view, update and delete extensions. As changes are made, again access the API endpoints to ensure changes are reflected.

**Comment by tombogle** [comment]
As a related task, I have updated the documentation in this [PR](https://github.com/paranext/extension-marketplace-services/pull/345). But that probably doesn't need to block this from being moved to Done.

**Comment by roopa0222** [comment]
I was able to update and delete an approved extension after I got the permissions on qa website.
However that ended up in causing issues on the extension side. 
filed a bug #1255
