### ISSUE TITLE
There should be an event that announces when a new function is available on a network object

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#149]
The title sums it up.  In addition, it would be interesting to include a version number along with each function.  A network object might choose to support multiple versions of the same function to help preserve backwards compatibility.

**Comment by FoolRunning** [comment]
This seems like a strange thing to add in. I would hope providers of network objects wouldn't just add new functions after registering the network object. Is there a use-case you have in mind that I'm not thinking of?

**Comment by lyonsil** [comment]
As things currently stand, adding a network object and adding a function on the network object are separate calls.  There is no notification to clients when new capabilities are added to the network (though we do have a notification when things are removed).  I'm suggesting that we tell clients when new things are added.  If we do #151, then this particular ticket probably isn't necessary.  If we don't do that one, then I think this one makes sense.

**Comment by tjcouch-sil** [comment]
Actually, the network object `.function` request is the actual function call on the network object. There is no discovering what functions are on a network object right now (ingestors just request `.function` and put a function name as the first element in the contents array in hopes that the network object has that function), but the contents of the `.get` function are an array so that, in the future, network objects can announce what functions they have.

**Comment by lyonsil** [comment]
>There is no discovering what functions are on a network object right now

Understood.  That's why I made this ticket. 😄

**Comment by lyonsil** [comment]
My comment about #151 above was incomplete.  If we do #151 (combine object and function registration into a single call) AND we do #148 (announce when new objects are created), presumably we don't need this, too.  #148 would presumably include the list of functions available on an object if #151 was done, too.

**Comment by lyonsil** [comment]
Doesn't make sense anymore given #1200
