### ISSUE TITLE
Load project data from non-Paratext 9 folder

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#181]
We need to make a way to have `ParatextData.dll` access a different project folder. We want Paranext to access a different directory of projects and resources.

Everything will be in the exact same data format as Paratext 9.

We also need to bundle an open source project or two into Paranext. Maybe we can grab WEB and OEB or something and convert it to Paratext format.

There are two files that are required to initialize `ParatextData.dll` that are not part of projects: `usfm.sty` and `en.ldml`. We need those in the file bundle.

**Comment by FoolRunning** [comment]
The USFM can be gotten from: https://github.com/ubsicap/usfm/tree/master/sty
The English LDML file can be gotten from: https://github.com/silnrsi/sldr/blob/master/sldr/e/en.xml (rename the XML extension)

**Comment by lyonsil** [comment]
This might be "tiny" for Windows, but it is far from tiny when we include Linux.

Here are some (but probably not all) things that need to change in ParatextData for this to work on current versions of Linux:
- [ ] Update ICU.net from version 2.8.1 to version 2.9.0.  [Functionality was added in 2.9.0](https://github.com/sillsdev/icu-dotnet/commit/0ab57ff02027cb9d1248ec8fd17f47952a5d3e13#diff-b50e994cb29a0a36086ad24043f3f413591a87ddc727ee111acdc8dbea95966f) that makes the `icu.net.dll.config` file work properly.
- [ ] Remove the lock in of using ICU version 59.  [ParatextData has a check](https://github.com/ubsicap/Paratext/blob/master/ParatextData/ICUDllLocator.cs#L52) related to whether FieldWorks is installed and should be used.  If FieldWorks is not installed, then we are locked into ICU version 59.  Newer versions of Linux are past that version, and there isn't a clean way to downgrade ICU in Linux.  Given the variety of Linux distributions and versions, it would be best to let ICU decide what version it should on its own unless we know that won't work for some reason.  It has its own logic to find installed versions.
- [ ] Either shim registry access so that we don't try to access registry keys when running outside of Windows or do a deeper scrub of all code paths Paranext will need to call to avoid using the registry when specific initialization options are provided.

To get past the first two issues I was able to produce a private build (on my dev box) of ParatextData.dll with these changes.  The third requires much deeper experience with Paratext than I have at the moment.

**Comment by FoolRunning** [comment]
Copying response I made in Discord:
> I'm guessing the problem is that the Linux build of Paratext has always been completely separate from the Windows build and kept on different branches. What we probably need to do is to look at the old Paratext Linux branch and see if we can pull some/all the changes into main without causing issues. I was hoping we wouldn't have to do that, but if you keep finding/fixing issues, then it's likely the branches are more different than I thought. 
> It might be worth talking to Tom Hindle who did 99.9% of the Linux work for Paratext (back when we supported Linux). Theoretically we only need changes that would affect a ParatextData.dll build (and it's dependencies).

**Comment by FoolRunning** [comment]
I found some descriptions of how we can create a [cross-platform NuGet package](https://medium.com/@yooonatan/creating-cross-platform-nuget-package-to-wrap-native-c-libraries-b2ee71c34164). I'm not entirely certain we'll need the native code for the tech demo, but we'll likely need some native libraries as we did deeper (e.g. Mercurial, TEKKit, etc.).

Also, it seems like someone else [had the same problem with the ICU library](https://github.com/sillsdev/libpalaso/pull/1250#issuecomment-1561386452) on Ubuntu 22. According to @lyonsil, it should just involve upgrading to a newer version of ICU.Net.

**Comment by lyonsil** [comment]
Here is a patch file with changes to Paratext (master branch) that Tim and I used to get `ParatextData.Initialize()` to work without throwing exceptions.  It seems unlikely these changes are what we really want to apply to ParatextData, but they give a sense of the important updates.

[linux-support.patch.txt](https://github.com/paranext/paranext-core/files/11558186/linux-support.patch.txt)
