### ISSUE TITLE
Add BCV to Toolbar

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#224]
Add the BCV (RefSelector) created earlier to the toolbar at the top.
It needs a data provider and styling.

Depends on #223 (Create the toolbar)

**Comment by tombogle** [comment]
There is a DRAFT [PR](https://github.com/paranext/paranext-core/pull/266) for this. It's now more-or-less working, but the ref selector control does not display nicely (Too tall, can't see the chapter or verse numbers at all, etc.), and there seems to be some problem with updating the control when the user clicks the next/prev buttons. Some of this used to work but no longer works after merging in the latest from main. Since @rolfheij-sil is more familiar with this control and it was agreed that I should turn my attention to https://github.com/paranext/paranext-extension-template/issues/28, I'm going to leave this for Rolf to try to finish when he gets back.

**Comment by jolierabideau** [comment]
I picked up the ticket to finish adjusting css.
