### ISSUE TITLE
Design menu contribution system

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#236]
We need to add a way to add to the menus in Paranext. It would be best to create a static data structure for extensions to list what menu additions they want in their `manifest.json` in order to support lazy loading extensions (#104). For now, this could be a simple design similar to VSCode's [menu contributions design](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) but significantly dumbed down.

Essentially, people would define menu items in their `manifest.json` files which would inform Paranext of a few details:
- Which menu
- Submenu(s)
- Display name
- Command to run
- [Later?] Icon
- [Later] Some kind of context in which to run

The extension host would aggregate all these menu items and send them to the renderer to create its menu with (maybe we could have a data provider on the extension host or something?).

The renderer would build out the menus with this information. When a user clicks a menu item, the renderer fires off that command.

[Menu design doc](https://docs.google.com/document/d/1nzLREjhttuJ_T4-kcB3RZj-oM4pDCk32D2oMkBcQTLY/edit#heading=h.j93mqi7pym8m)

**Comment by irahopkinson** [comment]
I believe Eric Gamma (one of the Gang of Four) really went to town using **Design Patterns** on VS Code's menu system. My guess would be the **Composite** pattern for the structure and the **Command** pattern when you click an item. Here is what ChatGPT had to say:

> The Composite pattern is a structural design pattern that allows you to treat individual objects and groups of objects uniformly. In the context of menus, it allows you to represent menu items and submenus in a hierarchical structure.
> 
> Here's how the Composite pattern can be applied to menus:
>
> **Component:** Define an abstract base class or interface called **Component** that represents both individual menu items and submenus. It should provide common operations such as `display()` for rendering the menu item/submenu and `add()` and `remove()` for adding or removing child components.
>
> **Leaf:** Implement the **Component** interface for individual menu items. These are the basic building blocks of the menu and cannot have any children. They provide the specific functionality for each menu item, such as executing a command when selected.
>
> **Composite:** Implement the **Component** interface for submenus. These are containers that can hold multiple menu items and submenus. The composite maintains a list of child components and delegates the `display()`, `add()`, and `remove()` operations to its children.
>
> By using the Composite pattern, you can create nested menus with varying levels of complexity. Each menu item can be treated uniformly, regardless of whether it is an individual item or a submenu. This pattern promotes code reusability, flexibility, and the ability to add new menu items or submenus without modifying the existing code.
>
> It's worth mentioning that this is just one possible design pattern for menus, and depending on your specific requirements, other patterns such as the Command pattern or the Builder pattern might also be applicable. The choice of pattern depends on the specific needs and complexity of your menu system.

**Comment by ianhewubs** [comment]
Drive-by comment: 
It may be worth thinking about how we decide to allow users to modify menus, specifically in Paratext. 
- Will all menus be customizable?
- Will some menus be immutable? (because it's hard to train people to use a tool if half the classroom's menus are different to the rest).  
- Will almost all menus be immutable and there is a "plugins" menu which is a free for all playground?

I can imagine it being really annoying for someone who develops a "Super Find" plugin to find they can't put it in the Edit menu (because Find is almost always in the Edit menu). Likewise I can imagine it being really annoying for someone trying to support a user who has installed several plugins that have changed the whole landscape of the menus in Paratext. Food for thought, hopefully!

**Comment by FoolRunning** [comment]
Another thing we need to consider is localization and how that works with defining where menus/sub menus should be.

**Comment by tjcouch-sil** [comment]
From Ian:
> if someone has localized the vanilla Paratext UI and someone adds a plugin, we'd either need to say at plugin install "This plugin isn't localized in Telegu it could look heckin' weird in your UI".

**Comment by ianhewubs** [comment]
> Ian suggested we add a warning when installing a plugin that isn't localized in your language.

After a few moments of thought, I'm thinking more along the lines of:

1. Make it clear to a user what languages any plugin is available in when they're browsing plugins.
2. Make "localization language" part of the filtering for the plugin browser 
... Warnings ought to be preventable here.

Incidentally, this is another reason that it would be great to be able to localize in-situ (maybe with some machine translation assistance, and maybe also report localizations back to the developers of Paratext/plugins). That way people might download a plugin, knowing that they may need to localize it, but in doing so they help other people working in their language.

**Comment by lyonsil** [comment]
Proposal:
- The core platform and all extensions will provide JSON documents that are combined into a single document.  The core platform's document has highest priority (i.e., is loaded first).  Any conflicts between documents should be resolved as best as possible (e.g., if some extension tries to create a duplicate menu item that already exists, that extension fails to load).
- The final JSON document must conform to the given schema document attached here.  JSON schema validation cannot perform all checks, but it's a good start.  [Lots of libraries and tool already exist](https://json-schema.org/implementations.html) that do this.  The platform will need to perform additional checks (e.g., all IDs in the JSON document must be unique, all localization IDs have associated localization strings, etc.).  All of those checks are not enumerated here and will require thought/input from the implementor(s).
- Once the final JSON document is loaded, a resource file (exact syntax still TBD, but some sort of key:value pairs) will be loaded that is used to replace all `locID` values in the JSON document.
- Once the JSON document is loaded with all of the localized strings, the platform should use it to render menus as needed based on UI actions.

I'm attaching a sample JSON file that includes a few menus and menu items for an example.  It's not complete, but it does validate against the schema.  Here are a few additional comments about the sample and schema:
- The file names end with `.txt` here because GitHub doesn't allow uploading `.json` files for whatever reason.
- Note that position numbers of menu items and menu groups don't have to be integers or sequential.  The idea is to just use them for sorting, and if someone wants to insert something in between menu items they can always pick a floating point number that is in between.  If we want to be picky about where items can be added, we can adjust the constraints.  I suspect UX will have opinions about this, and those opinions may or may not align with how extensibility works in Paratext now.
- I am enforcing a specific syntax for `locID`s to make sure they are clearly called out.  Also, I am considering all `locID`s to be in a global namespace.  I am against the idea of automatically generating those IDs based on other properties because it could cause all resource files to break with a very small code change.  Although the proposal is a bit tedious, it makes localization less likely to break on us later.
- I am expecting the only strings that will be displayed from the JSON file are the localized IDs.  Everything else is intended to be for internal use only within the platform.

Other comments:
- See the [Paranext Extension Architecture doc](https://docs.google.com/document/d/1nzLREjhttuJ_T4-kcB3RZj-oM4pDCk32D2oMkBcQTLY/edit#heading=h.iyxisjvfdp37) for examples of the various kinds of menus listed in the JSON schema.
- If JSON schema validation proves to be onerous/confusing to implement, it isn't technically required.  JSON schema is being used to convey the ideas and properties needed, and I thought it might be helpful to include in the implementation.  If it's more of a pain than a help to include in the implementation, don't get hung up on it.
- There are several online JSON schema validators.  I found https://json-everything.net/json-schema to be the most helpful of the bunch to use.  Error messages aren't always intuitive to find the problem, unfortunately.
- Keyboard navigation of menu items (e.g., making "E&xit" associated with the "x" key when navigating a menu by keyboard) is not addressed by this proposal.  I don't know if that is really important.  Even if it is, it might be easy enough to achieve by looking for ampersands in the localized strings and using the letter there as is how Windows native UI menus normally work.
- Ira's comments above apply at the level of how the menu system is written in code.  This proposal is about how menus can be contributed by extensions and how that can all work together with localization.  It's higher level than the code.
- What to do when a `locID` is encountered in the JSON document but doesn't have a corresponding resource for the UI language is not addressed in this proposal.  There are a lot of possibilities that include some of those listed above.  I would argue that while it is important, this design does not preclude most/all of those ideas and can move forward now to address the core, common case first.

[menu-schema.txt](https://github.com/paranext/paranext-core/files/12232576/menu-schema.txt)

[menu-sample.txt](https://github.com/paranext/paranext-core/files/12232577/menu-sample.txt)

**Comment by ianhewubs** [comment]
> I am expecting the only strings that will be displayed from the JSON file are the localized IDs

Would tooltips describing the menu item and/or keyboard shortcuts be stored in the JSON file or elsewhere? For example, "Show/hide Unicode" in the Edit menu in Paratext 9 has the tooltip and shortcut below:
>Toggle between Unicode character and Unicode number code
>Alt+X

The tooltip needs to be localizable. It would be nice if keyboard shortcuts were editable (currently they're not). I expect many people would keep the defaults, but there must be a whole host of anglo-centric shortcuts that make less sense once the UI is localized. I suspect that's something which we wouldn't rush to add immediately, but planning with it in mind would be wise.

**Comment by FoolRunning** [comment]
> (e.g., if some extension tries to create a duplicate menu item that already exists, that extension fails to load).

What do you mean by a duplicate menu item? Do you mean one that has the same text? Are we then going to check all languages? How does that work?

**Comment by lyonsil** [comment]
TJ had enough feedback that I moved all proposal updates to https://docs.google.com/document/d/1N9BVj5w1b3H90Sjjc1lRN2zbalL-beDHmh4jxxExtiw/edit?usp=drive_link.

@ianhewubs I added tooltips to the latest proposal.  Good thought, and it was trivial to add.  Keyboard shortcuts are not part of the spec right now, though.  While I can't say for certain until the a shortcut design is done, I think the framework I'm proposing could be extended since we're providing objects for each menu item.  For example, we could have "localizable" values for shortcuts just like the menu item strings.  I don't really know what all the goals are for customization, though.  For example, do we want users to be able to set their own?  That would have an impact to the design beyond different defaults for different languages.  All that being said, I'm going to consider it out of scope for the time being unless we simply can't ignore it.

@FoolRunning I was talking about this in terms of menu item IDs, but those are mostly gone in the latest design.  The only case where they remain in the design is that menu items that are anchors for submenus still have IDs in the latest spec.  There is also some language about what to do about ID collisions in the updated proposal.
