### ISSUE TITLE
Fix `papi.d.ts` not showing comments for services

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#292]
Follow-up from #166 

We need to fix the properties that are exposed on the `papi` so they have comments (like `webViews`, `EventEmitter`, etc).

For example, `papi.webViews` does not have JSDocs explaining what it is and how to use it:

![Image](https://github.com/paranext/paranext-core/assets/104016682/ce48e0ad-17ce-46f7-a7a2-329eade8bf87)

There aren't a ton of these service-level comments, so we need to create them on most of the services. But the `.d.ts` generation also does not currently carry them over.

**Comment by lyonsil** [comment]
The issue is that when assigning an object as a property of another object and then exporting the "outer" object, the comments of the "inner" object are not shown when looking at the pop up documentation for the outer object.

As background, it seems like VSCode only wants to show three kinds of docs from JSDocs.
1. Docs on the *direct object* you're working with (e.g., hovering over).
2. Docs on the *properties of the type of the direct object* you're working with.  I think this is represents [JSDoc typedefs](https://jsdoc.app/tags-typedef.html) in modern TypeScript.
3. Docs on the *function types* you're calling.  JSDoc comments are part of the types of functions and arrow functions when they are called, but docs are not part of function types being referenced as parameters.  I think this represents [JSDoc callbacks](https://jsdoc.app/tags-callback.html) in modern TypeScript.


Here is an example:
```
/** Foo comment */
type foo = {
  /** Bar comment */
  bar: string;
  /** Baz comment */
  baz: number;
};

/** MyObj comment */
const myObj: foo = { bar: 'aaa', baz: 4 };

const def = { somethingA: 3, somethingB: myObj, somethingC: myObj.bar };

/** MyFunc comment */
const myFunc = (num1: number) => {
  return num1.toString();
};

const output = myFunc(123);

interface myFuncInterface {
  someFunction: typeof myFunc;
  someFoo: typeof myObj;
}

const interfaceImpl: myFuncInterface = {
  someFunction: myFunc,
  someFoo: myObj,
};

interfaceImpl.someFunction(1);
interfaceImpl.someFoo;

// If you hover over "foo", "bar", "baz", or "myObj" anywhere, you see comments.
// You will never see comments about "foo" for "myObj", even if you remove the myObj comment.
// You will never see comments for "def" for any of the "something" A/B/C properties.
// You will see comments for "myFunc" when it is being used as a function.  When it is being referenced only as a property you won't.
// You will never see comments for "someFoo".

```

We are [not the first](https://stackoverflow.com/questions/74174052/why-dont-suggestion-descriptions-and-hover-info-for-typescript-object-propertie) to discover this.  [One SO post](https://stackoverflow.com/questions/73897734/how-to-add-description-to-a-property-type-so-that-intellisense-shows-it-in-vsco) had a potentially explanation why automatically showing details for the type of object provided might not even be desired.

So, to get comments from the `webViews` object exposed when working with `papi.webViews`, we would need comments to live in `papi.d.ts` literally at the point that the `webViews` property is defined for `papi`.  It can't be inherited from anything else like a type or an interface.

All this being said, it seems like we have to pick one of three options:
1. Leave comments where they are.  Direct service users (i.e., those not going through PAPI) will see the docs/comments, but PAPI users will not.
2. Move comments into PAPI.  PAPI users will see the docs/comments, but direct service users will not.
3. Keep duplicated comments in both places.

When I looked at something like option 3 in the past with the duplicate copies maintained by automated tools, the effort was going to be high and the resulting tools likely brittle over time.  So if we go with option 3, that probably means we shouldn't try something automated unless we have a clever idea for now to make it work.

I will ponder this a bit more and see if I can figure out another other alternatives.

**Comment by irahopkinson** [comment]
Thanks for finding this out and the good explanation. Presummably if you created `myFuncInterface` as a single nested object with comments they would all show up properly? Is that an option for us?

**Comment by lyonsil** [comment]
> Presummably if you created myFuncInterface as a single nested object with comments they would all show up properly?
Yes, that would be fine.

> Is that an option for us?
When TJ and I talked, we agreed we were trying to keep comments next to the module where it lived rather than in a separate file.  So it is technically an option (which I think would be equivalent to option 2) but not really desired.

I have a hacky idea I'm going to try today to give us option 4.  After that if there isn't a clear, good option then I think we have to pick the best of the bad options.
