### ISSUE TITLE
Make the .NET data provider production build process work properly

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#300]
On Windows, Ira was seeing that the assets folder wasn't found.  On Linux, Matt was seeing that the icu.net.dll.config file wasn't being provided along with the icu.net dependency.

Neither of these issues exists in the dev builds.

**Comment by tjcouch-sil** [comment]
Regarding the assets folder, for some context:

On the JavaScript side, the [main process finds a folder called the resources folder](https://github.com/paranext/paranext-core/blob/280-webpack/src/main/global-this.model.ts#L19) a bit differently in development and in production. In both, it first determines the resources path (built into electron builder):
- In production, it determines the resources path based on an electron-provided `process.resourcesPath` variable, which points to `<exe_dir>/resources`.
- In development, it determines the resources path to be the `paranext-core` root directory.
Then in both development and production, it takes the `resourcesPath` and adds `assets` to it. So it's either `paranext-core/assets` or `<exe_dir>/resources/assets` (I don't think this is your assets folder, but maybe this is some helpful context).

Then main passes the `resourcesPath` to the extension host via [command-line argument](https://github.com/paranext/paranext-core/blob/280-webpack/src/main/services/extension-host.service.ts#L97). Maybe you could do the same in `dotnet-data-provider.service.ts` as well if you wanted, but I don't think that's quite your goal. Just some information.

The resources path is significant because that's where all the `extraResources` files are put as you see them in [`electron-builder.json5`](https://github.com/paranext/paranext-core/blob/280-webpack/electron-builder.json5#L54) (note there are multiple `extraResources` listings under differnet operating systems and a shared one). That's how the dotnet project publish output is placed into the production version. I suppose your assets folder from the dotnet project isn't getting copied into the publish folder and therefore isn't being copied into the production build.

One thing you could try is moving your assets into the assets folder that's already present in the root. Or you could figure out a way to copy your assets folder in dotnet. Or you could add your folder to [`extraResources`](https://github.com/paranext/paranext-core/blob/280-webpack/electron-builder.json5#L331) and have electron builder copy it over. You could also do the same for the missing dll config file.

**Comment by lyonsil** [comment]
The C# project config lists the `assets` directory as something to always be copied:
```
    <Content Include="assets\**\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
```

Also, I see that it is indeed copied to the `Release` folder.  Whatever is doing post-dotnet packaging is not copying things recursively which is needed.

The missing `.config` file is a little more disturbing, because that comes from the package online, not us.  I could re-create it, but I don't know what else might be added in the future or what else might be downloaded along with other nuget packages that we aren't redistributing.  That needs further digging.

**Comment by tjcouch-sil** [comment]
> The C# project config lists the `assets` directory as something to always be copied:
> 
> ```
>     <Content Include="assets\**\*.*">
>       <CopyToOutputDirectory>Always</CopyToOutputDirectory>
>     </Content>
> ```
> 
> Also, I see that it is indeed copied to the `Release` folder. Whatever is doing post-dotnet packaging is not copying things recursively which is needed.
> 
> The missing `.config` file is a little more disturbing, because that comes from the package online, not us. I could re-create it, but I don't know what else might be added in the future or what else might be downloaded along with other nuget packages that we aren't redistributing. That needs further digging.

Ah good call on the recursive part. Looks like you can change what electron-builder copies over in `electron-builder.json5` on these dotnet lines (there are 3 - one for each os). Adding `/**` as pictured may do it, or you may need to do `/**/*`. Not sure

![image](https://github.com/paranext/paranext-core/assets/104016682/5f29c4e7-77bc-49b0-8406-5a65c924c0cf)

**Comment by lyonsil** [comment]
Turns out all the data was being copied properly.  We just weren't setting the cwd properly.  Also there were other build issues on Linux.
