### ISSUE TITLE
Create DockableUI Framework

### ISSUE THREAD

**Issue by darren8c** [paranext/paranext-core#31]
https://www.npmjs.com/package/rc-dock
https://github.com/tjcouch-sil/paranext-poc/tree/main/react-electron-poc

- [x] Choose a framework that is extensible and allows theming
- [x] Ability to add functionality to the docking framework

Determine how we can support the following:

- [x] Tabs
- [x] Draggable panels
- [x] Drop panels by location of mouse similar to PT9
- [ ] Autohide
- [x] Contextual area dropzones
- [x] Buttons in tabs
- [x] Buttons in tab groups
- [x] Floating Windows
- [ ] Ability to move dockable floating window to a separate window

Any features that we would need to write a lot of custom code for we should create issues to handle in the future.

**Comment by FoolRunning** [comment]
I looked at rc-dock and it supports basically everything we're wanting with a couple exceptions:
* It doesn't look like autohide is supported out of the box, but I think because of the way UX likely wants it to behave (i.e. only moving to autohide with an explicit command), I think we can create our own implementation fairly easily.
*  Tabs in a separate floating window can not dock the same way that Paratext 9 allows docking in floating windows. It looks like it only supports having multiple tabs in the same window. It's possible we might be able to work around this limitation or even change the code of rc-dock to allow the behavior we want.

**Comment by ianhewubs** [comment]
How concerned are we about interactions at this point? rc-dock does some of the things we want, but it uses a cross-shaped widget as a drop zone for moving panels. Would we be able to override that interaction model? UI the same as this tested catastrophically badly when we were making Paratext 9.0. Zero users were able to use it without coaching. 

We would want something which is at least as good as Paratext 9 for this. Ideally something even better because we know that some users still struggle to understand what the actual result of dropping a tab or panel will be. They need a more literal visual preview which shows "where tabs will move to if I drop this thing here" (similar to what OBS studio offers). 

There are several other things which are not in the checklist for this case which I would expect to see added. But my first concern is the interaction model.

**Comment by darren8c** [comment]
We are aware of the dropzones, and part of this issue was making sure the rc-dock handles theming.  We will want to capture pieces of the docking area that are not sufficient, but they may or may not be prioritized for the technology demonstration this year.  It will sort of depend on what other issues need to be prioritized for the tech demonstration to enable other areas and teams to work.  So this issue took a deep enough swing to help us feel confident we could code for  the areas that are probably deficient, but not in-depth enough to code for those.  If/When you have time to look through the docking solution and add issues as UX sees them we would welcome that as we know they exist.

**Comment by FoolRunning** [comment]
@ianhewubs, The docking code added to Paranext is using their drop-mode alteration (see [this example](https://ticlo.github.io/rc-dock/examples/#drop-mode)) which makes it behave very similarly to PT9.
