### ISSUE TITLE
Add extension ZIP cache directories to type roots and implement standalone extensions sharing types

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#365]
As an extension developer, I want to be able to reference types from other extensions when I'm writing code that depends on those extensions.

Extension ZIP files are decompressed by the extension service so they can be loaded and executed at runtime.  We would also like to use those decompressed `d.ts` files inside of VS Code when developing other extensions so we can use their types.

Platform.Bible conditionally unzips extensions into `paranext-core\dev-appdata\cache\extensions`. Let's leverage this.

1. Let's add `paranext-core\dev-appdata\cache\extensions` to `typeRoots`
2. We may need to make it so directory extensions' `.d.ts` files are copied into the extension cache in order to gather extension types from directories. However, that will probably mean the currently in development extension will have its `.d.ts` file twice, which could pose issues. Probably the solution at least for now is to make a short documentation about how to add other extensions' directories to your `typeRoots`
3. We may need to make it so if an extension is provided via a folder, the unzipped folder in the cache is deleted/not created. That way, if someone has a production version of an extension but is also developing the extension, they won't get duplicate types
4. Document this functionality where zipped extensions can be shared based on their `.d.ts` files put in the cache and note that it may be worth deleting this folder if you experience unexpected types issues.

**Comment by tjcouch-sil** [comment]
We should also think of a way to better support sharing types between extensions you're developing. Getting types from the cache would allow development off of other published extensions, but we don't have a clear way of doing that with in-development extensions right now. We might just have to teach people how to point `typeRoots` to the appropriate directory...

For an extension you're working on that already has a published version installed, Maybe we could detect when an extension is provided by a directory (instead of a zip) and delete the unzipped files in the cache.

**Comment by tjcouch-sil** [comment]
Turns out that `typeRoots` takes the first module definition it finds and ignores subsequent ones in order of its entries. Amazing! This means we can order `typeRoots` appropriately with the cache at the very end and other things before it and not have to worry about deleting cached stuff and whatnot.

Unfortunately, I discovered a few problems along the way:
- Using the existing `cache/extensions` folder doesn't work because TypeScript considers the folder name to be the module name, and all those folder names have a version number on them. Generally, the folder name for the extension doesn't technically *have* to match the extension name anyway. So I ended up making a `cache/extension-types` folder that contains folders that contain the types files.
  - Each folder in `cache/extension-types` is the name of the extension's TypeScript module (which should match the extension's name - see below). Inside that folder is the extension's `.d.ts` folder renamed to `index.d.ts` because this is the only file structure that TypeScript liked using without significant work to adjust it.
- I decided that, for consistency's sake, I'd assume the extension name is the module name in the extension's `.d.ts` file. I also assumed the extension's `.d.ts` file would be named `<extension_name>.d.ts`, `<extension_name><other-stuff>.d.ts`, or `index.d.ts`. We can add a `types` field to the `manifest.json` if we want, but it seemed not particularly necessary right now.
