### ISSUE TITLE
Create dialog service and Select Project dialog

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext-core#388]
As an extension developer, I want to be able to ask the user for some information using existing dialogs in Platform.Bible so it is easy for me to get information from users.

----

We need to create a dialog service that allows extensions to asynchronously ask the user for a response to something. There are some things we need to put in this service:
- [x] Select Project dialog
  - Share the UI with the open dialog #359
  - Can provide a title, prompt, etc
  - Returns a promise to the project id that the user selected
  - Would look something like `papi.dialogs.getProject` or something

If the linked issues are done first, just connect them into this dialog service. If not, just make sure they are put in with the issue in which they are to be created.

**Comment by tjcouch-sil** [comment]
I believe this is necessary for opening the Resource Viewer or Text Collection with a specified set of projects for the tech demo. @GlennPruitt

**Comment by irahopkinson** [comment]
Good UX means dialog primary buttons should always convey an action to take ususally using a verb. A secondary button (if it exists) is almost always the verb "Cancel". That means we shouldn't have any Yes/No dialogs. Remember that users essentially hate confirmation dialogs, usually don't read them and just want to get rid of them as quickly as possible. So confirmation dialogs should only be used rarely when it is crucial. Rather than use a confirmation dialog it is better to allow the user to undo the action or easily recreate the data so they have confidence to discover what things do.

**Comment by tjcouch-sil** [comment]
Select Multiple Projects split off to #514

**Comment by tjcouch-sil** [comment]
- [ ] Close dialog on confirm
- [ ] Close dialog on X
- [ ] List the actually installed projects
- [ ] DialogTab class
- [ ] Genericize
- [ ] Mapped types

**Comment by tjcouch-sil** [comment]
Created #551 for extensions creating dialogs

**Comment by tjcouch-sil** [comment]
Documentation:
- [`useDialogCallback`](https://github.com/paranext/paranext-extension-template/wiki/PAPI#usedialogcallback)
- [`papi.dialogs`](https://github.com/paranext/paranext-extension-template/wiki/PAPI#dialogs)
