### ISSUE TITLE
Create the WebView API

### ISSUE THREAD

**Issue by darren8c** [paranext/paranext-core#44]
Make webviews good. Make them persist, deserializeable, have api that controls the webview and the webview panel, etc.

Depends on #45, #31

**Comment by irahopkinson** [comment]
After PR #167, adding an extension that adds a WebView will automatically add a tab in the dock layout after with the existing extension tabs. When adding a WebView, there is now a new `layoutType` property which defaults to _tab_. The other options of _panel_ and _float_ have not yet been implemented until we can specify exactly where in the dock layout a item should be added. If an extention's WebView is removed the tab will be blank. The tab can be closed by the user but is not currently automatically removed.

Before and after this PR, WebViews don't survive a reload (browser refresh), i.e. the extension tabs will be blank. This will require some re-working of PAPI to enable reload to still show extensions on a reload.

**Comment by irahopkinson** [comment]
Do note, since it's now saving the layout, if you close tabs they might not come back since we have no way currently to require them to. To fix this:

1. After a fresh restart/start, in **Developer Tools**, click **Application**.
2. Expand **Local Storage** and click **`http://localhost:1212/`**.
3. Delete the _dock-saved-layout_ key and value.
4. Restart.

**Comment by irahopkinson** [comment]
After PR #173, you can close WebView tabs and they will come back on a restart.
