### ISSUE TITLE
Fix Memory Leaks

### ISSUE THREAD

**Issue by katherinejensen00** [paranext/paranext-core#587]
1. Run a memory profiler
2. Fix major memory leaks the profiler reveals that don't occur on shutdown

**Comment by katherinejensen00** [comment]
Timeboxed to a medium

**Comment by FoolRunning** [comment]
My preliminary analysis seems to point to what I expected - that the biggest memory leaks are caused by event handlers that are not getting unsubscribed. I'm going to look into how we can get them unsubscribed when needed.


![Image](https://github.com/paranext/paranext-core/assets/4229836/cc6cc330-26c8-4497-95b3-07bfdb03b85d)

**Comment by FoolRunning** [comment]
This may be fixed by #578.

**Comment by FoolRunning** [comment]
After looking into this problem after #578 was completed, it seems that that case fixed this memory leak problem as well.
