### ISSUE TITLE
Error while building types

### ISSUE THREAD

**Issue by ryderwishart** [paranext/paranext-core#774]
**To Reproduce**

1. clone repo
2. `npm i`
3. `npm run build:types`
4. See error:

```
> build:types
> cd lib/papi-dts && npm run build


> papi-dts@0.0.1 build
> tsc && prettier --write papi.d.ts && ts-node edit-papi-d-ts.ts && prettier --write papi.d.ts

[warn] Ignored unknown option { tsdoc: true }.
papi.d.ts 287ms (unchanged)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/ryderwishart/paranext-core/lib/papi-dts/edit-papi-d-ts.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Hooks.load (node:internal/modules/esm/hooks:383:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

I'm running on a Mac M1.

**Comment by lyonsil** [comment]
Hey @ryderwishart , sorry for the trouble.  This is a known issue with ts-node right now.  It's [mentioned](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide#error-committing-or-running-npm-run-buildtypes-typeerror-err_unknown_file_extension-unknown-file-extension-ts-for-usersuserdevparanext-corelibpapi-dtsedit-papi-d-tsts) in our [troubleshooting guide on the wiki](https://github.com/paranext/paranext/wiki/Troubleshooting-Guide).

One thing to note about Macs is that the platform will run overall, but the .NET process won't do much for you yet.  If you're on Discord, I know you can ask @jolierabideau for tips as she also has been doing dev work on her Mac.

**Comment by tjcouch-sil** [comment]
Decided to go ahead and work on updating to Node LTS v20.11.1 :)
[Updated to node 20.11.1 LTS by tjcouch-sil · Pull Request #64 · paranext/paranext-extension-template](https://github.com/paranext/paranext-extension-template/pull/64)
[Updated to node 20.11.1 LTS by tjcouch-sil · Pull Request #12 · paranext/paranext-multi-extension-template](https://github.com/paranext/paranext-multi-extension-template/pull/12)

**Comment by ryderwishart** [comment]
I was able to start the app, thanks @tjcouch-sil for the quick fix!!

> One thing to note about Macs is that the platform will run overall, but the .NET process won't do much for you yet.

@lyonsil, can you help me understand this better? I don't have any context or idea of what this means, except that I can see that the app is failing to parse John 11:35 apparently (unless that's just some default content in there at the moment and it's not actually trying to parse anything).

**Comment by lyonsil** [comment]
@ryderwishart The .NET process is our way of getting to Paratext resources.  Those resources are currently the only way to get scripture data in the platform.

If you want to read all the low level details about what problems we're having see #264 . At a high level, Unicode (ICU) libraries are macOS are not the same as what we have on Linux and Windows.  A part-time volunteer who is familiar with development on Macs who is working on the problem. Until the issue is resolved, everything except scripture access should be working, but that is obviously a big hole.

If you have some straightforward APIs or other ways of getting scripture data, then perhaps this isn't a big blocker for you.  As a desktop application for translators who are working on local projects, we know this has to be resolved if they are going to be able to use Macs.  For developers, though, there are other ways around this if you have other APIs you're using.

If you'd like to talk about this in more detail please feel free to reach out on Discord or email and we can have a longer discussion or video chat.
