### ISSUE TITLE
Checks: Create Checks Result List webview

### ISSUE THREAD

**Issue by lyonsil** [paranext/paranext-core#881]
As a member of the translation team, I want to be able to see and interact with the results of running checks on my project.

Assume we will recreate something similar to what was done in PT9 unless UX has a different design in place.

From PT9:

![Image](https://github.com/paranext/paranext-core/assets/128563279/ee42ef78-b340-4f32-8592-9d5e5273fd06)

**Comment by tombogle** [comment]
This is more-or-less done. There's a small amount of work to do to hook up the rerun action so that the Reerun button will display and can be used to regenerate the test data, but I wanted to get this into review before disappearing for a few days. I'm not exactly sure if the Rerun button is even something that UX will want. If so and someone else wants to hook it up, great. otherwise, I'll do it next week.

**Comment by ianhewubs** [comment]
> I'm not exactly sure if the Rerun button is even something that UX will want. 

In PT9 "Rerun" is the key to finding out whether your fixes really fixed anything. "Are there fewer errors when I press rerun?"
If in PT10 how will the checks run? Are they always running or will they be triggered by the user manually. If they're ever triggered manually, a rerun button would be essential.

**Comment by lyonsil** [comment]
> If in PT10 how will the checks run?
The intent (at least initially) is for users to enable checks to run automatically but not require it. That is not a locked in decision but how we're thinking about it right now. I'm assuming we will still allow manual runs.

**Comment by tombogle** [comment]
For the case where users maybe don't want the checks to auto-run, it's possible that it might make sense to have an accordion control at the top that can be expanded to show each check (rather than a comma-separated list that runs off the screen). Then there could be a re-run button associated with each check, perhaps in addition to a "re-run all" button.

**Comment by Sebastian-ubs** [comment]
Hi, for a future design of the result list ux envisions different changes. We are happy to involve you @tombogle in person or just throw the idea into the design efforts. For now we think that it's probably the best to merge the PR with the current style / components and follow up with other iteration(s). If you like to do a small adjustment in here, you may change the button `variant` to `ghost` for the buttons inside of the table component.

Meanwhile it would make sense to talk through with devs if there is any generic tree component that we would like to create or consume (e.g. from external [shadcn-extension](https://github.com/BelkacemYerfa/shadcn-extension) or [shadcn#355](https://github.com/shadcn-ui/ui/issues/355)). Then conder using this tree as a base for the reference list component.

**Comment by tombogle** [comment]
I definitely don't _need_ to be part of that discussion, but I'm willing to participate if you would find it helpful (as long as it's after June 29). Since I'm still tweaking things, I did switch buttons to "ghost". Unexpectedly, that messed up the appearance of the indentation, but happily that got me looking at the Tailwind styling problem and I think I've solved the mystery!
I did briefly poke around looking at possible tree implementations (actually before I saw your comment). Assuming we can find (or create) something suitable, the probably is the way to go. At least for now, my implementation more-or-less functions like a tree.

**Comment by roopa0222** [comment]
Feedback for testing from Tom
You can check that each of the grouping options works as expected, that the Rerun button produces new results and updates the time. Also if you expand or collapse any groups, those should be remembered when you rerun, so for example, if Luke was expanded and you rerun, if there is still an error in Luke, it should remain expanded. If there is no error in Luke, but then you rerun and a new error appears for Luke, it should still be expanded. (There is probably room for future enhancements, such as adding expand-all and collapse-all buttons or maybe automatically expanding results for the current book.) 
+
Also check that if you click a detail row (no matter which grouping option is selected), that row appears selected (subtle change in the background color) and any previous row selection is cleared.

**Comment by roopa0222** [comment]
Verified the Checks Result List based on the feedback. The functionality of grouping is working as it is supposed to.
The style of the display list is working as it is supposed to.

However, the scroll bar feature is missing when there are more results displayed. 

![Scripture-Book-Type-2](https://github.com/user-attachments/assets/8faa446f-146c-49b0-8cbe-a6aa6848edbc)
