### ISSUE TITLE
Be able to use Tailwind classes in extensions

### ISSUE THREAD

**Issue by Sebastian-ubs** [paranext/paranext-core#978]
**User Story**
As a extension developer, I want to be able to build UIs using the shared componentns so that we can achive a consistent look and feel.

**Description**
Investigate
- [ ] how to enable Tailwind in extensions & share Tailwind styles from paranext-core with extensions
- [ ] where best to develop which level of components
  - how to understand / decide this as a developer
  - who is responsible if components end up at one or the other place
  - consider benefits in development speed and shareability for one or the other place

Do
- [ ] implement it
- [ ] document and communicate it

References:
- https://discord.com/channels/1064938364597436416/1250162847594582026/1252662483257397269
- https://discord.com/channels/1064938364597436416/1253038969201885204/1253068930545881209

**Comment by tjcouch-sil** [comment]
If we need shadcn in the templates, I wonder if `${configDir}` would be useful for implementing path aliases https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-configdir-template-variable-for-configuration-files

**Comment by tjcouch-sil** [comment]
Looks like there is an online tool (not an npm package) made for adding a tailwind prefix to existing code, which would be helpful in getting people to add `tw-` to their existing code to make it work well in an extension https://github.vue.tailwind-prefix.cbass.dev/

Since this isn't an npm package, people wouldn't be able to do this automatically. But they could pull code from https://github.com/vesper8/vue-tailwind-prefix-applicator and make it happen.

**Comment by tjcouch-sil** [comment]
BTW discussion thread around this issue https://discord.com/channels/1064938364597436416/1289269993724313621/1289270016784470057
